##############################################################################
################################# makefile ###################################
##############################################################################
#		                                                                     #
#   makefile of CQKnPClone                                                   #
#                                                                            #
#   Input:  $(CQKCDIR) = the directory where the source is                   #
#           $(CQKH)   = the include file(s) for CQKnPClass.h                 #
#           $(CQKINC) = the -I$(CQKnPClass directory)                        #
#                                                                            #
#   Output: $(CQKCH)   = the .h files to include                             #
#           $(CQKCINC) = the -I$(include directories)                        #
#									                                         #
#                                VERSION 1.00	                             #
#                                17 - 05 - 2012                              #
#                                                                            #
#                              Antonio Frangioni                             #
#                            Operations Research Group                       #
#                           Dipartimento di Informatica	                     #
#                            Universita' di Pisa                             #
#                                                                            #
##############################################################################

# macroes to be exported- - - - - - - - - - - - - - - - - - - - - - - - - - -

CQKCINC = -I$(CQKCDIR) $(CQKINC)
CQKCH = $(CQKCDIR)CQKnPClone.h

############################ End of makefile #################################
